### ISSUE TITLE
Add instructions for GistPress on custom post meta fields

### ISSUE THREAD

**Issue by GaryJones** [bradyvercher/gistpress#52]
Some folks store content in custom fields (post meta), so it would be handy for them to have instructions and a code snippet they can drop in so that GistPress (in fact, any oembed parsing) can run on their particular post meta key content.

See `WP_Embed::__construct()` for a starting point.

**Comment by bradyvercher** [comment]
So you're looking to process oEmbeds in an arbitrary blob of content without all the formatting provided by the `the_content` filter?

**Comment by GaryJones** [comment]
Me personally, no, but someone asked for it :-)

Think of a CPT that has custom fields for splitting up different parts of the content - perhaps an introduction, the bulk of a code tutorial, and then a conclusion. At the moment, I don't think our shortcode or oEmbed URL would be recognised and parsed in a custom field. I realise that instructions we give are probably going to be to enable all oEmbed support for that field, rather than just GistPress, but if there's a way of also limiting it to just GistPress, even better.

I'm not saying this should be enabled by default (we don't know the post meta key anyway) - just have the instructions and example snaippet for how to enable it in the readme.
