### ISSUE TITLE
Won't display the code, just the pasted url

### ISSUE THREAD

**Issue by lmartins** [bradyvercher/gistpress#53]
Hi,

I've tested Gistpress before without any issues, but now I can't get it to display the gists on the site frontend. In the backend shows the loading animation when I paste the URL, but on the front-end it just displays the URL:

http://intangible.life/modern-wordpress-workflow-task-automation/

What should I look before to debug this?

**Comment by GaryJones** [comment]
Got to check the obvious first - is it installed? http://intangible.life/wp-content/plugins/gistpress/README.md is showing up as 404.

**Comment by lmartins** [comment]
omg... hides in shame.
The issue first appeared on my local install and I just assumed I'd already installed the plugin on the server too. Sorry about that Gary.

Im getting a "Internal Error" in the content editor preview box, but indeed it's already showing something on the front-end that I now need to apply better styling. 

Thanks for your help.

**Comment by GaryJones** [comment]
I've opened #54 for the Internal Error problem.
