### ISSUE TITLE
Content Editor Preview

### ISSUE THREAD

**Issue by GaryJones** [bradyvercher/gistpress#54]
As reported at https://github.com/bradyvercher/gistpress/issues/53#issuecomment-89770579 the updated content editor that previews embedded media shows an Internal Error. It would be good to either show a rendering, or otherwise avoid the obvious error.

**Comment by bradyvercher** [comment]
Were you able to replicate the internal error? I'm not sure how to reproduce that.

Rendering the actual code might be a bit overwhelming for long snippets. That API is still experimental as well, so there's no commitment to backward compatibility, which has already caused issues in a different plugin I maintain.

**Comment by GaryJones** [comment]
Tagging @lmartins in case he can replicate or debug the cause of the error.

**Comment by lmartins** [comment]
I'll check if I can access the server logs to see if get something there.

**Comment by nurtext** [comment]
Btw: Any progress on this? Would be nice to have a editor preview for both URLs and shortcodes. Is there a WP API that's needs to be called by the plugin in order to get this working?

**Comment by GaryJones** [comment]
The last day or two, I've been playing with Shortcake (Shortcode UI), which offers preview of shortcodes in the Editor. So, no actual progress with this yet, but Shortcake (and it's potential inclusion in WP core) would seem a sensible way to go. See #56.

**Comment by bradyvercher** [comment]
Closing in favor of #75.
