### ISSUE TITLE
Add Shortcake support

### ISSUE THREAD

**Issue by GaryJones** [bradyvercher/gistpress#56]
Shortcake is a visual interface for crafting shortcodes. It would be interesting to have that for Gists, and have it show up as a preview in the editor.

**Comment by bradyvercher** [comment]
I gave Shortcake a quick whirl and it's pretty slick. Adding support looks really easy, but a couple of things that might need to be worked out:

1. It doesn't appear to work with oEmbed URLs
2. Support needs to be added for every attribute since it takes over shortcode management

**Comment by GaryJones** [comment]
I've used Shortcake for a current project, and you're right on both points. However, the list of fields is not too painful.

oEmbed URLs may well have more trouble, sure.

**Comment by bradyvercher** [comment]
Shortcake seems to have lot momentum. Rather than rely on an extra plugin, we could build support directly into the media manager. I've got a few ideas that might be fun to work on if we get some of the other stuff out of the way first.

**Comment by bradyvercher** [comment]
Closing in favor of #75.
