### ISSUE TITLE
Plugin doesn't activate

### ISSUE THREAD

**Issue by GaryJones** [bradyvercher/gistpress#58]
I'm not sure why, but on one multi-site install, on one site, GistPress refuses to activate.

On subdomain 1, it doesn't activate - although the "Plugin activated" message appears, it's is neither highlighted as being active, nor parses shortcodes / oembed correctly.
On subdomain 2, GistPress is already active.
On subdomain 3, GistPress is not active, but has no issues with being activated and deactivated.

As it's a live site, I've not yet disabled other plugins or custom theme to see if there's a conflict.

**Comment by schlessera** [comment]
Some additional info that might help diagnosing:
- I made an exact copy of the site on my local machine (using VVV-VV, Wordmove & WP Migrate DB Pro), and it activated without issues on that local copy.
- Activation on the local copy did not throw any errors as far as I can tell.
- The local copy was already activated, which means that it was activated for the DB on the live site too, despite the plugin screen showing it differently.
- When I network-activate on the live site, it works without issues/notices.

**Comment by bradyvercher** [comment]
I honestly haven't heard of anything like this happening before. Any progress on figuring out if it's a plugin conflict? Or could something be filtering the `active_plugins` option or is it being truncated somehow?
