### ISSUE TITLE
Stylesheet not loaded properly

### ISSUE THREAD

**Issue by Nilpo** [bradyvercher/gistpress#62]
The stylesheet does not load properly.  Developer tools shows that it is loading a badly formed URL

`https://gist.github.comhttps//assets-cdn.github.com/assets/gist-embed-7346e9a735aaeeacede51d1efaad6208f95d9edbc222155878bfddc2da28fa87.css?ver=4.4.2`

**Comment by bradyvercher** [comment]
Hi @Nilpo, I'm not having any luck replicating this. Are you running the latest version ([v3.0.1](https://github.com/bradyvercher/gistpress/releases/tag/v3.0.1))?

**Comment by Nilpo** [comment]
Yes I am.  I was having this same problem on an older version and updated hoping it would fix it.

**Comment by Nilpo** [comment]
And now it's working. I think there was an issue with caching.  I'm running both local caching and Cloudflare.
