### ISSUE TITLE
Stray doctype html validation error when using gistpress

### ISSUE THREAD

**Issue by jdelia** [bradyvercher/gistpress#63]
When using gistpress - it is inserting a stray doctype html and body tags generating errors in the validator. Issue seen on multiple websites including your own site [http://www.cedaro.com/](url)

See this line in your code: [https://github.com/bradyvercher/gistpress/blob/develop/includes/class-gistpress.php#L472](url)

<img width="1356" alt="screen shot 2016-03-19 at 1 47 17 pm" src="https://cloud.githubusercontent.com/assets/3217274/13900286/27790100-edd9-11e5-997f-061a652767ee.png">

[https://validator.w3.org/nu/?doc=https%3A%2F%2Fjackiedelia.com%2Fadding-svg-logo-utility-pro-theme%2F](url)

**Comment by GaryJones** [comment]
@bradyvercher I think after the [HTML is dumped](https://github.com/bradyvercher/gistpress/blob/develop/includes/class-gistpress.php#L530) out of the DOMDocument object, we'll need to strip the `doctype`, `html` and `body` elements that preceed / wrap around the `div` we're really interested in.

**Comment by Nilpo** [comment]
I believe I have a solution for this. Let me pull the latest code and test it.

**Comment by GaryJones** [comment]
Closed in #64.
