### ISSUE TITLE
Selecting lines not working with WP 4.5.2

### ISSUE THREAD

**Issue by marcelstoer** [bradyvercher/gistpress#66]
## Expected Behavior
`[gist id="bb88f9d4c3436b0d311416ada53c13a7" file="file-validate-email.php" lines="34-44"]` should display lines 34-44.

## Current Behavior
There's just a link to the Gist by ID: https://gist.github.com/bb88f9d4c3436b0d311416ada53c13a7

## Steps to Reproduce (for bugs)
1. Use WP 4.5.2.
2. Install latest GistPress release or latest from the develop branch.
3. Use gist short code as above.

## Your Environment
GistPress installed on my server at http://frightanic.com/blog/wp-content/plugins/gistpress/README.md.

**Comment by bradyvercher** [comment]
Hi @marcelstoer, as I mentioned in #67, it looks like the issue here is that the value in the `file` attribute is incorrect. Can you update that and let me know if everything works correctly?

**Comment by GaryJones** [comment]
@marcelstoer Any feedback?

**Comment by marcelstoer** [comment]
That was indeed the problem, thanks. Sorry for not responding earlier.
