### ISSUE TITLE
Check how gists look on AMP pages

### ISSUE THREAD

**Issue by GaryJones** [bradyvercher/gistpress#69]
AMP pages use a limited set of HTML elements, and strip everything else out.
## Expected Behaviour

Ideally, if the gist can't be displayed correctly, we'd just leave a clear link to the exact gist ID, file and line number as needed.
## Current Behavior

No idea - but it should be tested.
## Possible Solution

I'm really not even sure how we'd test if the current page is being shown in an AMP context.

**Comment by GaryJones** [comment]
https://github.com/Automattic/amp-wp#handling-media

Looks like there might be some custom embed handler we could use, that would allow at least something to be displayed, instead of it getting stripped out completely.

**Comment by anythinggraphic** [comment]
Awesome!!

**Comment by GaryJones** [comment]
There is now an [`amp-gist` component](https://www.ampproject.org/docs/reference/components/amp-gist).
