### ISSUE TITLE
GistPress mis-rendering line selections and special characters

### ISSUE THREAD

**Issue by kevinsullivan** [bradyvercher/gistpress#70]
Jetpack properly renders code written for the lean prover, from GitHub, but this plug-in does not. It does select the correct lines to render, but renders them within large blank areas around them, which makes it not useful. Worse, it mis-renders special characters in the code.  You can see what's going on by visiting this page, at least for as long as it lasts: https://learnfunctionalprogramming.com/2017/03/26/welcome-dependent-type-theoretical-foundations-programming/. Jetpack correctly renders the gist initially, but then you can see that this plug-in mis-renders it immediately below.

**Comment by bradyvercher** [comment]
Hi @kevinsullivan, I've tested this locally without any problems -- with and without Jetpack active. Here are a few things you you might try:

* Make sure you're using the latest version of GistPress
* Try disabling Jetpack to see if there's a conflict between the two plugins
* Ensure you don't have any unbalanced HTML tags in your post or theme
* Try updating the post to flush the GistPress cache

I'm currently seeing extra `<html>` and `<body>` tags around the GistPress output in your markup, which is strange, but I'm not able to reproduce that locally.
