### ISSUE TITLE
Plug-in abandoned?

### ISSUE THREAD

**Issue by kevinsullivan** [bradyvercher/gistpress#71]
Seems that this plug-in has been abandoned. Is that a fair assessment? Thanks.

**Comment by bradyvercher** [comment]
No, that's not a fair assessment. The plugin has been stable for some time and bugs are fixed as they're reported. New features aren't a priority, but may be implemented as time permits.

By the way, your previous issue ( #70 ) received a response a few hours after you opened it and is awaiting a reply.

**Comment by GaryJones** [comment]
The plugin is in active use, and we're both keeping an eye on new reports. A stable well built plugin means there aren't many plugins to attend to, and while there are a few issues open for new features, they aren't for something either us or a contributor has a need to get done quickly.
