### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function set_logger()

### ISSUE THREAD

**Issue by robneu** [bradyvercher/gistpress#72]
When using WP-CLI on a PHP 7 Pagely VPS the above error error causes WP-CLI to fail completely.

## Possible Solution
Checking `$gistpress instanceof GistPress` in `gistpress_init` seems to resolve the issue.

## Your Environment
* Version used: 2.0.3
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): PHP 7.0.15
* Server type and version: Pagely VPS (AWS)
* Operating System and version: Ubuntu 16.04 LTS

**Comment by bradyvercher** [comment]
Looks good to me. I'll try to merge and release a new version this afternoon or tomorrow.

**Comment by GaryJones** [comment]
In what circumstance is this error being triggered? How is `gistpress_init()` being called without the global being populated without it being an instance of `GistPress`?

**Comment by robneu** [comment]
It happens when attempting to run any WP-CLI command on a box running PHP 7+. The only way I was able to avoid it was to tell WP-CLI to skip loading plugins.

I haven't investigated any further than that.
