### ISSUE TITLE
Gist Shows Without Tabs

### ISSUE THREAD

**Issue by joshuadavidnelson** [bradyvercher/gistpress#74]
For some time now my embedded gists have shown up without the lines tabbed (so everything is left-aligned). I haven't modified any styling on my theme, but I have kept the plugin updated (currently at version 3.0.0).

You can view an example [here](https://joshuadnelson.com/programmatically-add-images-to-media-library/) versus in GitHub [here](https://gist.github.com/joshuadavidnelson/164a0a0744f0693d5746#file-create-image-id-php).

**Comment by bradyvercher** [comment]
It looks like tab characters are being converted to spaces somewhere along the way. Do you have some code or a plugin that might be doing that? You'll likely need to update the post after deactivating any plugins to flush the cache.

**Comment by joshuadavidnelson** [comment]
Hmmm... I shouldn't, but I'm guessing this is just me seeing this error. I'll dig into it later this evening on my local environment to see if there's a plugin conflict. Thanks!

**Comment by GaryJones** [comment]
CSS all looks fine - `white-space:pre` coming from Github's CSS etc.

**Comment by joshuadavidnelson** [comment]
Weird - must be something on my setup conflicting with it. Thanks for the quick responses, guys - sorry if I wasted your time. I'll circle back if I find a bug/conflict.

**Comment by GaryJones** [comment]
@joshuadavidnelson Looking at the `view-source:` for your page, shows that your HTML is being minified. Maybe try turning this off temporarily, or adding an exclusion for the `div.gist` element.

**Comment by joshuadavidnelson** [comment]
Thanks for the tip. I'm using WP Rocket. I turned off minification, bumped the gist shortcode, cleared the cache, opened incognito. Still see it. I'm guessing it's something on my end, though, not a bug with the plugin at this point. Thanks for the assistance!

**Comment by wpsmithtwc** [comment]
I did some testing and this is most likely due to HTML minification (or at least it was for me).
