### ISSUE TITLE
Add GistPress block for Gutenberg

### ISSUE THREAD

**Issue by GaryJones** [bradyvercher/gistpress#75]
The new Gutenberg editor seems ripe for us to consider adding a GistPress Embed block, with all of the current shortcode attributes mapped to block attributes.

## Expected Behavior

Quick couple of mockups, as example:

![screenshot 2017-06-19 13 04 19](https://user-images.githubusercontent.com/88371/27284267-d7c9b846-54ef-11e7-8c35-d812e07b6d3f.png)
![screenshot 2017-06-19 13 10 50](https://user-images.githubusercontent.com/88371/27284457-bc2c83d8-54f0-11e7-8b76-5239eacb7018.png)

## Current Behavior
None

## Possible Solution
Gists inserted with GistPress naturally fit into the block system that Gutenberg uses.

## Steps to Produce
1. Decide on whether the neutral view (after first inserting a block) should ask for the Gist ID / URL (like the Embed block asks for a URL).
2. Register block, attributes.
3. Display attributes in settings panel, with any descriptions as needed.
3. Try and get a basic preview working.
4. Adapt preview to represent what the block attributes are set as.
5. Support width / alignment attributes like image blocks do?
6. Don't break when used on a site that doesn't use Gutenberg Editor.

**Comment by GaryJones** [comment]
Linking to https://github.com/pantheon-systems/github-gist-gutenberg-block/issues/5#issuecomment-433203303 as a possible starting point for a GistPress block.

**Comment by redrockapps** [comment]
Here's a plugin of mine that adds Gist ability to the Gutenberg Editor for reference: [Gistr WP Plugin](https://wordpress.org/plugins/gistr/)

**Comment by westerdaled** [comment]
Tried both the Gistr ( embed block) & GistPress ( html block) .  Both impressive, with the former having the edge through ease of use. Maybe you should combine code bases 😉
