### ISSUE TITLE
Suspected encoding problem with umlauts

### ISSUE THREAD

**Issue by nils-a** [bradyvercher/gistpress#76]
## Expected Behavior
The gist should be displayed, as it is in github - using the "correct" encoding

## Current Behavior
is is not. Instead of an "ä" I am seeing "Ã¤" - this is "normal" if UTF8 is treated as ASCII.

## Steps to Reproduce (for bugs)
see the gist at: https://gist.github.com/nils-a/60e687103f4dafc853f7292c29780efa/#file-concatenateallwordfiles-vba (line 3)
and compare to https://blog.nils-andresen.de/2011/03/word-dokumente-zusammenfassen.html

## Context
I feel this is a minor problem, as not many people are using german umlauts in their code :-)

## Your Environment
* GistPress v 3.0.1
* WP v 5.3.2
* PHP v 7.0.33
* Some server, somewhere running cloudLinux

**Comment by GaryJones** [comment]
<img width="282" alt="Screenshot 2020-01-07 at 16 47 57" src="https://user-images.githubusercontent.com/88371/71912479-7c032a80-316d-11ea-808d-bdb0ec7bf2f0.png">

Confirming that it's coming from the [API](https://gist.github.com/nils-a/60e687103f4dafc853f7292c29780efa.json) correctly.
